language: node_js
node_js:
  - "stable"
os:
  - linux
before_install:
  - export CHROME_BIN=chromium-browser
  - export FIREFOX_BIN=firefox
services:
 - xvfb
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm install
  - node_modules/karma/bin/karma start karma.conf.js --single-run
after_script: node_modules/grunt-cli/bin/grunt coverage
notifications:
  slack: mtr-design:8Hj8yAQDcHqPZKpylxbalk9K