dist: xenial
language: node_js
node_js:
  - "stable"
os:
  - linux
sudo: required
addons:
  chrome: stable
  firefox: latest
env:
  global:
    - MOZ_HEADLESS=1
before_install:
  - export CHROME_BIN=chromium-browser
  - export FIREFOX_BIN=firefox
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost & ⋮
script:
  - npm install
  - node_modules/karma/bin/karma start karma.conf.js --single-run
after_script: node_modules/grunt-cli/bin/grunt coverage
notifications:
  slack: mtr-design:8Hj8yAQDcHqPZKpylxbalk9K