language: node_js
node_js:
  - "stable"
os:
  - linux
before_install:
  - export CHROME_BIN=chromium-browser
  - export FIREFOX_BIN=firefox
services:
 - xvfb
script:
  - npm install
  - node_modules/karma/bin/karma start karma.conf.js --single-run
after_script: node_modules/grunt-cli/bin/grunt coverage
notifications:
  slack: mtr-design:8Hj8yAQDcHqPZKpylxbalk9K