language: node_js
node_js:
  - "13.5.0"
os:
  - linux
before_install:
  - export CHROME_BIN=chromium-browser
  - export FIREFOX_BIN=firefox
  - export DISPLAY=:99.0
services:
 - xvfb
before_script:
  - npm install
script: node_modules/karma/bin/karma start karma.conf.js --single-run
after_script: node_modules/grunt-cli/bin/grunt coverage
notifications:
  slack: mtr-design:8Hj8yAQDcHqPZKpylxbalk9K